apiVersion: v1
kind: Service
metadata:
  name: emailimagesobserver-service
  labels:
    run: emailimagesobserver
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: emailimagesobserver