apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - <your-domain-prefix>.<your-location>.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - <your-domain-prefix>.<your-location>.cloudapp.azure.com
  issuerRef:
    name: <ca-name>
    kind: ClusterIssuer
