apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - <domain>
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - <domain>
  issuerRef:
    name: <ca-name>
    kind: ClusterIssuer
