apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: <ca-name>
spec:
  acme:
    server: <acme-server-url>
    email: <your-email-address>
    privateKeySecretRef:
      name: <ca-name>
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
