kind: ConfigMap
apiVersion: v1
metadata:
  name: erabliere-iu-oidc
data:
  oauth-oidc.json: |
    {
      "apiUrl": "<oidc.apiUrl>",
      "clientId": "<oidc.clientId>",
      "tenantId": "<oidc.tenantId>",
      "scopes": "<oidc.scopes>",
      "appRoot": "<oidc.appRoot>",
      "authEnable": true
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-startup
data:
  k8s-startup.sh: |
    #!/bin/bash
    echo 'k8s-startup script'
    echo 'remove default oidc config'
    rm /app/wwwroot/assets/config/*.json

    echo 'copy mounted oidc config into the asset/config directory'
    cp /app/mountconfig/oauth-oidc.json /app/wwwroot/assets/config/oauth-oidc.json

    echo 'create the secret folder'
    mkdir /app/secret

    echo 'copy the email config'
    cp /app/mountsecret/emailConfig.json /app/secret/emailConfig.json

    echo 'startup the api'
    dotnet ErabliereApi.dll

---