apiVersion: v1
kind: Service
metadata:
  name: fhir-db-service
  labels:
    run: fhirdb
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
  selector:
    app: fhirdb