alertmanager:
  ingress:
    enabled: true
    annotations: {kubernetes.io/ingress.class: "nginx"}
    labels: {}
    hosts:
      - alertmanager.freddycoder.com
    paths:
      - /
grafana:
  ingress:
    enabled: true
    annotations: {kubernetes.io/ingress.class: "nginx"}
    labels: {}
    hosts:
      - grafana.freddycoder.com
    paths:
      - /
prometheus:
  ingress:
    enabled: true
    annotations: {kubernetes.io/ingress.class: "nginx"}
    labels: {}
    hosts:
      - prometheus.freddycoder.com
    paths:
      - /