apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevopsteammembersvelocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredevopsteammembersvelocity
  template:
    metadata:
      labels:
        app: azuredevopsteammembersvelocity
    spec:
      containers:
      - name: azuredevopsteammembersvelocity
        image: erabliereapi/azuredevopsteammembersvelocity:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: Forwarded_headers
          value: "true"
        - name: USE_SCHEMA_FROM_PROXY
          value: "true"
        - name: DevOpsProxyCacheSeconds
          value: "3"
        - name: AzureAD__ClientId
          value: "<azuread-clientid>"
        - name: AzureAD__TenantId
          value: "<azuread-tenantid>"
        - name: REDIS_HOSTNAME
          value: redis-service
        resources:
          limits:
            cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: azuredevopsteammembersvelocity
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: azuredevopsteammembersvelocity
