kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: erabliere-api-storage
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: erabliere-api-data
  annotations:
    volume.beta.kubernetes.io/storage-class: erabliere-api-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi